import type { OrderRole } from "./roles";

export type ProductCategory = OrderRole;

export type WeeklyProduct = {
  id: string;
  name: string;
  defaultQty: number;
  unit: string;
  note?: string;
  category: ProductCategory;
};

export const weekLabel = "WEEK 1 — June 29-July 3, 2026";

export const weeklyProducts: WeeklyProduct[] = [
  { id: "vegetables-fruits-banana-lakatan", name: "Banana, lakatan", defaultQty: 35.0, unit: "kg", category: "vegetables_fruits" },
  { id: "vegetables-fruits-bell-pepper", name: "Bell Pepper", defaultQty: 35.0, unit: "kg", category: "vegetables_fruits" },
  { id: "vegetables-fruits-bell-pepper-red-and-green", name: "Bell Pepper (Red and Green)", defaultQty: 8.0, unit: "kg", category: "vegetables_fruits" },
  { id: "vegetables-fruits-bell-pepper-red", name: "bell pepper (red)", defaultQty: 16.5, unit: "kg", category: "vegetables_fruits" },
  { id: "vegetables-fruits-carrots", name: "Carrots", defaultQty: 148.0, unit: "kg", category: "vegetables_fruits" },
  { id: "vegetables-fruits-garlic", name: "Garlic", defaultQty: 26.5, unit: "kg", category: "vegetables_fruits" },
  { id: "vegetables-fruits-ginger", name: "Ginger", defaultQty: 4.25, unit: "kg", category: "vegetables_fruits" },
  { id: "vegetables-fruits-kalamansi", name: "Kalamansi", defaultQty: 3.0, unit: "kg", category: "vegetables_fruits" },
  { id: "vegetables-fruits-onion-white", name: "Onion white", defaultQty: 2.0, unit: "kg", category: "vegetables_fruits" },
  { id: "vegetables-fruits-onion", name: "Onion", defaultQty: 28.0, unit: "kg", category: "vegetables_fruits" },
  { id: "vegetables-fruits-onion-red", name: "Onion Red", defaultQty: 14.0, unit: "kg", category: "vegetables_fruits" },
  { id: "vegetables-fruits-papaya", name: "Papaya", defaultQty: 20.0, unit: "kg", category: "vegetables_fruits" },
  { id: "vegetables-fruits-papaya-or-sayote", name: "papaya or Sayote", defaultQty: 21.0, unit: "kg", category: "vegetables_fruits" },
  { id: "vegetables-fruits-sayote", name: "Sayote", defaultQty: 60.0, unit: "kg", category: "vegetables_fruits" },
  { id: "vegetables-fruits-potato", name: "Potato", defaultQty: 138.0, unit: "kg", category: "vegetables_fruits" },
  { id: "vegetables-fruits-sili-haba-pangsigang", name: "Sili haba( Pangsigang)", defaultQty: 1.0, unit: "kg", category: "vegetables_fruits" },
  { id: "meat-chicken-breast", name: "Chicken (Breast)", defaultQty: 433.0, unit: "kg", category: "meat" },
  { id: "meat-chicken-drumstick", name: "Chicken (Drumstick)", defaultQty: 46.0, unit: "kg", category: "meat" },
  { id: "meat-chicken-whole", name: "Chicken (Whole)", defaultQty: 55.0, unit: "kg", category: "meat" },
  { id: "meat-chicken-breast-drumstick", name: "Chicken breast/drumstick", defaultQty: 30.0, unit: "kg", category: "meat" },
  { id: "meat-chicken-giniling", name: "Chicken Giniling", defaultQty: 30.0, unit: "kg", category: "meat" },
  { id: "meat-ground-chicken", name: "Ground Chicken", defaultQty: 19.5, unit: "kg", category: "meat" },
  { id: "meat-ground-pork", name: "Ground Pork", defaultQty: 136.5, unit: "kg", category: "meat" },
  { id: "meat-pork-kasim", name: "Pork (Kasim)", defaultQty: 96.0, unit: "kg", category: "meat" },
  { id: "meat-pork-giniling", name: "Pork Giniling", defaultQty: 26.0, unit: "kg", category: "meat" },
  { id: "meat-pork-kasim-lomo", name: "Pork Kasim/Lomo", defaultQty: 90.0, unit: "kg", category: "meat" },
  { id: "meat-pork-liver", name: "Pork Liver", defaultQty: 8.0, unit: "kg", category: "meat" },
  { id: "meat-pork-lomo", name: "Pork lomo", defaultQty: 14.0, unit: "kg", category: "meat" },
  { id: "fish-egg-egg-medium", name: "Egg (Medium)", defaultQty: 17.0, unit: "tray", category: "fish_egg" },
  { id: "fish-egg-egg-small", name: "egg (small)", defaultQty: 8.0, unit: "tray", category: "fish_egg" },
  { id: "fish-egg-eggs", name: "Eggs", defaultQty: 4.0, unit: "tray", category: "fish_egg" },
  { id: "fish-egg-fish-fillet-dory", name: "Fish Fillet (Dory)", defaultQty: 326.0, unit: "kg", category: "fish_egg" },
  { id: "groceries-all-purpose-flour", name: "All Purpose Flour", defaultQty: 44.5, unit: "kg", category: "groceries" },
  { id: "groceries-banana-ketchup", name: "Banana Ketchup", defaultQty: 4.0, unit: "gallon", category: "groceries" },
  { id: "groceries-bayleaf-50-g-pack", name: "bayleaf 50 g/pack", defaultQty: 4.0, unit: "pack", category: "groceries" },
  { id: "groceries-block-ground-papper100g-pack", name: "block ground papper100g/pack", defaultQty: 1.0, unit: "pack", category: "groceries" },
  { id: "groceries-black-pepper-powder", name: "black Pepper Powder", defaultQty: 1.0, unit: "kg", category: "groceries" },
  { id: "groceries-black-pepper-ground-kg", name: "Black Pepper, Ground ,  \u00bdkg", defaultQty: 5.0, unit: "packs", category: "groceries" },
  { id: "groceries-black-pepper-ground", name: "Black pepper Ground", defaultQty: 2.5, unit: "kg", category: "groceries" },
  { id: "groceries-black-pepper-ground-500g", name: "black pepper Ground 500g", defaultQty: 1.0, unit: "pack", category: "groceries" },
  { id: "groceries-block-pepper-granules-50-g-pack", name: "block pepper (granules) 50 g/pack", defaultQty: 12.0, unit: "pack", category: "groceries" },
  { id: "groceries-breading-mix-garlic", name: "Breading Mix (Garlic)", defaultQty: 1.0, unit: "pack", category: "groceries" },
  { id: "groceries-breading-mix", name: "Breading mix", defaultQty: 5.0, unit: "kg", category: "groceries" },
  { id: "groceries-butter", name: "Butter", defaultQty: 2.0, unit: "pc", category: "groceries" },
  { id: "groceries-bread-crumbs", name: "Bread crumbs", defaultQty: 5.0, unit: "kg", category: "groceries" },
  { id: "groceries-cooking-oil-1l", name: "Cooking oil 1L", defaultQty: 7.0, unit: "liter", category: "groceries" },
  { id: "groceries-cooking-oil", name: "Cooking oil", defaultQty: 30.0, unit: "liter", category: "groceries" },
  { id: "groceries-cooking-oil-2l", name: "Cooking oil 2L", defaultQty: 8.0, unit: "bottles", category: "groceries" },
  { id: "groceries-catsup-1-kilo", name: "Catsup 1 kilo", defaultQty: 1.0, unit: "gallon", category: "groceries" },
  { id: "groceries-chicken-pork-cubes-60-cubes", name: "Chicken/Pork Cubes 60 cubes", defaultQty: 1.0, unit: "tub", category: "groceries" },
  { id: "groceries-cling-wrap-12-x500m", name: "Cling wrap 12\"x500m", defaultQty: 1.0, unit: "roll", category: "groceries" },
  { id: "groceries-corn-kernel-425g", name: "Corn Kernel 425g", defaultQty: 41.0, unit: "can", category: "groceries" },
  { id: "groceries-cornstrach", name: "CornStrach", defaultQty: 1.0, unit: "kg", category: "groceries" },
  { id: "groceries-fish-sauce", name: "Fish Sauce", defaultQty: 11.0, unit: "liter", category: "groceries" },
  { id: "groceries-fish-sauce-300ml", name: "Fish Sauce 300ml", defaultQty: 1.0, unit: "liter", category: "groceries" },
  { id: "groceries-garbage-plastic-black-large", name: "Garbage plastic black Large", defaultQty: 20.0, unit: "roll", category: "groceries" },
  { id: "groceries-iodized-salt", name: "Iodized Salt", defaultQty: 11.5, unit: "kg", category: "groceries" },
  { id: "groceries-laurel-leaves-100g", name: "Laurel Leaves, 100g", defaultQty: 2.0, unit: "pack", category: "groceries" },
  { id: "groceries-laurel-leaves", name: "Laurel leaves", defaultQty: 5.0, unit: "pack", category: "groceries" },
  { id: "groceries-liquid-seaoning-250ml", name: "Liquid Seaoning, 250ml", defaultQty: 1.0, unit: "bottles", category: "groceries" },
  { id: "groceries-liquid-seasoning", name: "Liquid Seasoning", defaultQty: 1.5, unit: "bottles", category: "groceries" },
  { id: "groceries-liquid-seasoning-500ml-bottle", name: "liquid seasoning 500ML/bottle", defaultQty: 6.0, unit: "bottles", category: "groceries" },
  { id: "groceries-liquid-seasoning-100g-pack", name: "Liquid Seasoning 100g/pack", defaultQty: 2.0, unit: "pack", category: "groceries" },
  { id: "groceries-mixed-butter-vegetables-1-kilo-pack", name: "Mixed Butter Vegetables 1 kilo/pack", defaultQty: 7.5, unit: "pack", category: "groceries" },
  { id: "groceries-mixed-butter-vegetables-250g-pack", name: "Mixed Butter Vegetables 250g/pack", defaultQty: 8.0, unit: "pack", category: "groceries" },
  { id: "groceries-mixed-vegetables-500g-carrots-green-peas-corn", name: "Mixed Vegetables (500g) (Carrots, Green Peas, Corn)", defaultQty: 90.0, unit: "pack", category: "groceries" },
  { id: "groceries-oyster-sauce", name: "Oyster sauce", defaultQty: 3.0, unit: "liter", category: "groceries" },
  { id: "groceries-oyster-sauce-405g", name: "Oyster Sauce (405g)", defaultQty: 8.0, unit: "bottles", category: "groceries" },
  { id: "groceries-oyster-sauce-500ml", name: "Oyster Sauce 500ml", defaultQty: 1.0, unit: "bottles", category: "groceries" },
  { id: "groceries-pine-apple-chunks-108oz", name: "Pine Apple Chunks 108oz", defaultQty: 5.0, unit: "can", category: "groceries" },
  { id: "groceries-pine-apple-chunks-822g", name: "Pine Apple Chunks, 822g", defaultQty: 8.0, unit: "can", category: "groceries" },
  { id: "groceries-pineapple-chunks-432g", name: "Pineapple Chunks (432g)", defaultQty: 17.0, unit: "can", category: "groceries" },
  { id: "groceries-pineapple-chunks-200g", name: "Pineapple chunks, 200g", defaultQty: 40.0, unit: "pack", category: "groceries" },
  { id: "groceries-pinaapple-chuck", name: "Pinaapple Chuck", defaultQty: 25.0, unit: "can", category: "groceries" },
  { id: "groceries-rice-kg", name: "Rice Kg", defaultQty: 155.0, unit: "kg", category: "groceries" },
  { id: "groceries-rice-sack", name: "Rice Sack", defaultQty: 34.0, unit: "sack", category: "groceries" },
  { id: "groceries-soy-sauce", name: "Soy Sauce", defaultQty: 49.5, unit: "liter", category: "groceries" },
  { id: "groceries-soy-sauce-1liter-bottle", name: "soy sauce 1liter/bottle", defaultQty: 7.0, unit: "bottles", category: "groceries" },
  { id: "groceries-soy-sauce-gallon", name: "Soy Sauce Gallon", defaultQty: 2.0, unit: "gallon", category: "groceries" },
  { id: "groceries-spring-oil", name: "Spring Oil", defaultQty: 2.0, unit: "gallon", category: "groceries" },
  { id: "groceries-spring-oil-1-5-l-bottle", name: "Spring Oil (1.5 L / bottle)", defaultQty: 4.0, unit: "bottles", category: "groceries" },
  { id: "groceries-sugar", name: "Sugar", defaultQty: 3.0, unit: "kg", category: "groceries" },
  { id: "groceries-sugar-white", name: "sugar (white)", defaultQty: 7.0, unit: "kg", category: "groceries" },
  { id: "groceries-sugar-washed", name: "Sugar Washed", defaultQty: 4.0, unit: "kg", category: "groceries" },
  { id: "groceries-sugar-segunda", name: "Sugar Segunda", defaultQty: 1.0, unit: "kg", category: "groceries" },
  { id: "groceries-tomato-sauce-kilo", name: "tomato sauce kilo", defaultQty: 24.0, unit: "kg", category: "groceries" },
  { id: "groceries-tomato-sauce-liter", name: "tomato sauce liter", defaultQty: 2.0, unit: "liter", category: "groceries" },
  { id: "groceries-tomato-sauce-900g", name: "Tomato Sauce (900g)", defaultQty: 15.0, unit: "pack", category: "groceries" },
  { id: "groceries-vinegar-gallon", name: "Vinegar gallon", defaultQty: 2.0, unit: "gallon", category: "groceries" },
  { id: "groceries-vinegar-liter", name: "Vinegar Liter", defaultQty: 15.0, unit: "liter", category: "groceries" },
  { id: "groceries-vinegar-bottles", name: "Vinegar Bottles", defaultQty: 2.0, unit: "gallon", category: "groceries" },
  { id: "other-order-apron", name: "Apron", defaultQty: 1, unit: "pc", category: "other_order" },
  { id: "other-order-kitchen-hand-gloves-100-s", name: "Kitchen Hand Gloves, 100's", defaultQty: 1, unit: "pc", category: "other_order" },
  { id: "other-order-lpg-kitchen-gas-with-tank-11kg", name: "LPG (kitchen gas) with tank, 11kg", defaultQty: 1, unit: "pc", category: "other_order" },
  { id: "other-order-lpg-hose", name: "LPG Hose", defaultQty: 1, unit: "pc", category: "other_order" },
  { id: "other-order-lpg-tank-refill-11kgs", name: "LPG Tank, Refill, 11kgs", defaultQty: 1, unit: "pc", category: "other_order" },
  { id: "other-order-single-burner-gas-stove-heavy-duty", name: "Single Burner Gas Stove, Heavy Duty", defaultQty: 1, unit: "pc", category: "other_order" },
];

export { orderRoleLabels as categoryLabels } from "./roles";
